services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "*.nikpetrich.net"
      SITES: "inventory.nikpetrich.net=https://www.youtube.com/"

volumes:
  ssl_data:
