services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    network_mode: host
    environment:
      ALLOWED_DOMAINS: "*nikpetrich.net"
      SITES: "inventory.nikpetrich.net=http://localhost:1112"

volumes:
  ssl_data:
