services:
  # This is for sharing the ssl certificates between the services
  redis:
    image: redis:alpine
    command: redis-server --requirepass "${REDIS_PASSWORD}"  # Optional: secure with a password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"  # Expose for debugging, optional

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl-data:/etc/resty-auto-ssl
    network_mode: host
    environment:
      - ALLOWED_DOMAINS=nikpetrich.net  # The domain of your server
      - SITES=dice.nikpetrich.net=http://localhost:1111;inventory.nikpetrich.net=http://localhost:1112;  # The subdomains and their corresponding ports
      - STORAGE_ADAPTER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_KEY_PREFIX=ssl_  # Optional: prefix for keys
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # If password is set
    depends_on:
      - redis

volumes:
  redis-data:
  ssl-data: