services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "([a-z]+.)?nikpetrich.net"
      SITES: "dice.nikpetrich.net=http://localhost:1111/; inventory.nikpetrich.net=http://localhost:1112/"

volumes:
  ssl_data:
