services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "nikpetrich.net"
      SITES: "nikpetrich.net=http://frontend:80"
    networks:
      - reverse-proxy_default
      - erp_default

networks:
  reverse-proxy_default:
    external: true
  erp_default:
    external: true

volumes:
  ssl_data:
